name = "systemeprompt"
main = "_worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "CASHFLOW_KV"
id = "106db6da016d49d2b480452f19bad695"
[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "univers-livres"

[vars]
SITE_URL = "https://univers.nyxia.top"
SYSTEME_ACTIVATION_FIELD = "lien_activation_nyxia"
SYSTEME_ACTIVATION_TAG_ID = "2221814"
SYSTEME_RESET_FIELD = "nyxia_reset_url"
SYSTEME_RESET_TAG_ID = "2223012"
